# Generated by Django 5.1.7 on 2025-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithor', '0002_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
    ]
